CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS semantic_roles (
    id BIGSERIAL PRIMARY KEY,
    role_name TEXT NOT NULL UNIQUE,
    description TEXT,
    category TEXT,
    parent_role_id BIGINT REFERENCES semantic_roles(id),
    embedding_model TEXT,
    embedding_vector vector(1536),
    aliases JSONB DEFAULT '[]'::jsonb,
    keywords JSONB DEFAULT '[]'::jsonb,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_semantic_roles_role_name ON semantic_roles(role_name);
CREATE INDEX idx_semantic_roles_category ON semantic_roles(category);
CREATE INDEX idx_semantic_roles_aliases ON semantic_roles USING GIN (aliases);
CREATE INDEX idx_semantic_roles_keywords ON semantic_roles USING GIN (keywords);

-- CREATE INDEX idx_semantic_roles_embedding
-- ON semantic_roles
-- USING ivfflat (embedding_vector vector_cosine_ops);

INSERT INTO semantic_roles (role_name, description, category) VALUES
('object_id', 'Unique ArcGIS/internal object identifier', 'system'),
('global_id', 'Globally unique GIS identifier', 'system'),
('created_date', 'Record creation timestamp', 'audit'),
('created_user', 'User who created the record', 'audit'),
('last_edited_date', 'Last edit timestamp', 'audit'),
('last_edited_user', 'User who last edited the record', 'audit'),
('last_update_date', 'Last source update timestamp', 'audit'),
('site_address', 'Primary site or property address', 'address'),
('street_address', 'Street address text', 'address'),
('street_name', 'Street name', 'address'),
('street_prefix', 'Street directional prefix', 'address'),
('street_suffix', 'Street directional suffix', 'address'),
('street_type', 'Street type such as Rd, Ave, Blvd', 'address'),
('unit_number', 'Apartment or suite number', 'address'),
('address_number', 'Numeric address component', 'address'),
('city', 'City or municipality name', 'address'),
('county', 'County name', 'address'),
('state', 'State or province name', 'address'),
('zip_code', 'Postal or ZIP code', 'address'),
('parcel_id', 'Parcel identifier', 'property'),
('property_id', 'Property identifier', 'property'),
('account_id', 'Account identifier', 'property'),
('account_number', 'Account number', 'property'),
('owner_name', 'Property or asset owner name', 'people'),
('applicant_name', 'Applicant or requestor name', 'people'),
('business_name', 'Business or organization name', 'people'),
('zoning_code', 'Short zoning classification code', 'zoning'),
('zoning_description', 'Human readable zoning description', 'zoning'),
('land_use', 'Land use classification', 'zoning'),
('flood_zone', 'Flood zone classification', 'environment'),
('permit_number', 'Permit identifier number', 'permits'),
('permit_type', 'Permit type classification', 'permits'),
('permit_status', 'Permit workflow or approval status', 'permits'),
('approved_date', 'Approval date', 'permits'),
('road_name', 'Road or street name', 'transportation'),
('road_classification', 'Road functional classification', 'transportation'),
('asset_id', 'Infrastructure asset identifier', 'utilities'),
('utility_asset_id', 'Utility infrastructure asset identifier', 'utilities'),
('hydrant_id', 'Hydrant identifier', 'utilities'),
('valve_id', 'Valve identifier', 'utilities'),
('meter_id', 'Meter identifier', 'utilities'),
('manhole_id', 'Manhole identifier', 'utilities'),
('cleanout_id', 'Sewer cleanout identifier', 'utilities'),
('water_main', 'Water main infrastructure feature', 'utilities'),
('sewer_main', 'Sewer main infrastructure feature', 'utilities'),
('pressure_main', 'Pressurized utility main', 'utilities'),
('gravity_main', 'Gravity-fed utility main', 'utilities'),
('geometry', 'Spatial geometry field', 'geometry'),
('shape_area', 'Calculated geometry area', 'geometry'),
('shape_length', 'Calculated geometry length', 'geometry'),
('geometry_area', 'Geometry area measurement', 'geometry'),
('geometry_length', 'Geometry length measurement', 'geometry'),
('latitude', 'Latitude coordinate', 'geospatial'),
('longitude', 'Longitude coordinate', 'geospatial'),
('elevation', 'Elevation value', 'geospatial'),
('height', 'Height measurement', 'geospatial'),
('acres', 'Area in acres', 'geospatial'),
('acreage', 'Property acreage', 'geospatial'),
('city_boundary', 'Municipal boundary geometry', 'boundaries'),
('parcel_boundary', 'Parcel boundary geometry', 'boundaries'),
('floodplain_boundary', 'Floodplain boundary geometry', 'boundaries'),
('zoning_boundary', 'Zoning district boundary geometry', 'boundaries'),
('phone_number', 'Telephone number', 'contact'),
('email_address', 'Email address', 'contact'),
('website_url', 'Website URL', 'contact'),
('active_flag', 'Boolean active/inactive indicator', 'status'),
('status', 'Generic workflow or lifecycle status', 'status'),
('comments', 'Freeform comments or notes', 'text'),
('description', 'Human readable description', 'text'),
('ordinance_number', 'Ordinance identifier number', 'legal'),
('ordinance_adopted_date', 'Date ordinance was adopted', 'legal'),
('ordinance_change_date', 'Date ordinance was modified', 'legal');


INSERT INTO semantic_roles (role_name, description, category)
VALUES
('install_date', 'Date infrastructure or asset was installed', 'audit'),
('date_updated', 'Date record or feature was updated', 'audit'),
('expiration_date', 'Expiration or end validity date', 'audit'),
('effective_date', 'Date record or rule became effective', 'audit'),
('maintenance_by', 'Maintaining organization or department', 'operations'),
('info', 'Generic informational text field', 'text'),
('owned_by', 'Owning organization or entity', 'ownership'),
('operation_date', 'Operational event date', 'operations'),
('facility_id', 'Facility identifier', 'facilities'),
('gc_modify_date', 'GIS change or modify timestamp', 'audit'),
('speed_limit', 'Road speed limit value', 'transportation'),
('service_begin_date', 'Service begin/start date', 'operations'),
('photo_reference', 'Photo or image reference', 'media'),
('sum_flow', 'Summarized flow measurement', 'utilities'),
('service_end_date', 'Service end date', 'operations'),
('generic_date', 'Generic date field', 'audit'),
('emergency_service_number_left', 'Emergency service number left side', 'public_safety'),
('road_created_date', 'Road feature creation date', 'transportation'),
('district_agency_id', 'District or agency identifier', 'administrative'),
('entered_by', 'User who entered the record', 'audit'),
('service_number', 'Service request or service identifier', 'operations'),
('start_date', 'Start date', 'audit'),
('end_date', 'End date', 'audit'),
('gps_date', 'GPS capture or collection date', 'geospatial'),
('material_type', 'Infrastructure or asset material type', 'utilities'),
('verified_date', 'Date record was verified', 'audit'),
('completion_date', 'Completion date', 'operations'),
('gc_exception', 'GIS or geocoding exception indicator', 'system'),
('interior_depth', 'Interior or infrastructure depth measurement', 'utilities'),
('pipe_size_in', 'Inbound pipe size measurement', 'utilities'),
('pipe_size_out', 'Outbound pipe size measurement', 'utilities'),
('park_name', 'Park or recreational area name', 'places'),
('work_order_date', 'Work order date', 'operations')
ON CONFLICT (role_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS field_semantic_candidates (
    id BIGSERIAL PRIMARY KEY,
    field_id BIGINT NOT NULL REFERENCES arcgis_fields(id),
    semantic_role_id BIGINT NOT NULL REFERENCES semantic_roles(id),
    similarity_score NUMERIC NOT NULL,
    rank INTEGER NOT NULL,
    method TEXT DEFAULT 'embedding',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (field_id, semantic_role_id)
);
